export const CHAO_HOI = "chao_hoi"
export const GIOI_THIEU = "gioi_thieu"
export const HIEN_DANH_SACH = "hien_danh_sach"
export const THONG_TIN_O_TO = "thong_tin_o_to"
export const THEM_O_TO = "them_o_to"
export const KHONG_TIM_THAY = "khong_tim_thay"
